# Generated by Django 4.1.5 on 2023-02-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="cover",
            field=models.ImageField(null=True, upload_to="img/post/"),
        ),
    ]
