# Generated by Django 4.1.5 on 2023-02-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_job_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(max_length=6000),
        ),
    ]
