# Generated by Django 4.1.5 on 2023-02-23 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_alter_job_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="job.customer",
            ),
        ),
    ]
