# Generated by Django 4.1.5 on 2023-02-23 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_alter_job_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_nature",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="job.customer"
            ),
        ),
    ]
