# Generated by Django 4.1.5 on 2023-02-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0005_job_job_nature_alter_job_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancer",
            name="name_job",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
