# Generated by Django 4.1.5 on 2023-02-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_freelancer_name_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="apply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yourname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("link", models.CharField(max_length=100)),
                ("cv", models.FileField(null=True, upload_to="service/cv/")),
                ("coverletter", models.TextField(max_length=1000)),
            ],
        ),
    ]
