# Generated by Django 4.1.4 on 2023-02-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0008_apply_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apply",
            name="yourname",
        ),
    ]
