# Generated by Django 4.1.4 on 2023-02-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0010_alter_apply_coverletter_alter_apply_cv_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apply",
            name="coverletter",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="apply",
            name="cv",
            field=models.FileField(null=True, upload_to="service/cv/"),
        ),
        migrations.AlterField(
            model_name="apply",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="apply",
            name="link",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="apply",
            name="username",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
