# Generated by Django 4.1.4 on 2023-02-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0011_alter_apply_coverletter_alter_apply_cv_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apply",
            name="username",
            field=models.CharField(default="test", max_length=50),
            preserve_default=False,
        ),
    ]
