# Generated by Django 4.1.4 on 2023-02-27 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0012_alter_apply_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply",
            name="job",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="job.job"
            ),
        ),
    ]
