# Generated by Django 4.1.4 on 2023-03-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0013_apply_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freelancer",
            name="category",
        ),
        migrations.AddField(
            model_name="freelancer",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="job.category",
            ),
        ),
    ]
